[2022-09-05  13:30:26.438] base.py -> post_method line:39 [INFO] : case_id:1 - 登录测试
[2022-09-05  13:30:27.458] base.py -> post_method line:50 [ERROR] : 响应失败--HTTPConnectionPool(host='127.0.0.1', port=8888): Max retries exceeded with url: http://cloud-gateway-test.ifyou.net/uc/api/code/getsms (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002290470D0C0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
[2022-09-05  13:30:27.459] base.py -> equal line:108 [ERROR] : 失败原因：'NoneType' object has no attribute 'json'
[2022-09-05  13:30:27.463] base.py -> post_method line:39 [INFO] : case_id:2 - 登录测试
[2022-09-05  13:30:28.466] base.py -> post_method line:50 [ERROR] : 响应失败--HTTPConnectionPool(host='127.0.0.1', port=8888): Max retries exceeded with url: http://cloud-gateway-test.ifyou.net/uc/api/code/getsms (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000229047571C0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
[2022-09-05  13:30:28.477] base.py -> equal line:108 [ERROR] : 失败原因：'NoneType' object has no attribute 'json'
